/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audience` | `/audience`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/engage` | `/engage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/partners` | `/partners`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/audience` | `/audience`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/engage` | `/engage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/partners` | `/partners`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/agenda${`?${string}` | `#${string}` | ''}` | `/agenda${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/audience${`?${string}` | `#${string}` | ''}` | `/audience${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/engage${`?${string}` | `#${string}` | ''}` | `/engage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/feed${`?${string}` | `#${string}` | ''}` | `/feed${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/partners${`?${string}` | `#${string}` | ''}` | `/partners${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/agenda` | `/agenda`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/audience` | `/audience`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/engage` | `/engage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feed` | `/feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/partners` | `/partners`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
